/*
  ==============================================================================

    Configs.h
    Created: 24 Oct 2025 4:17:11pm
    Author:  MayTigerStation

  ==============================================================================
*/

#pragma once

// set defines for different configurations

#define SCREEN_WIDTH 975
#define SCREEN_HEIGHT 650

#define FPS 60

// Slider values and positions

#define TILE_SLIDER_WIDTH 28
#define TILE_SLIDER_HEIGHT 11
#define TILE_SLIDER_BG_WIDTH 40
#define TILE_SLIDER_BG_HEIGHT 67
#define TILE_SLIDER_STARTING_X 145
#define TILE_SLIDER_GAP_X 51

#define COSTUME_KNOB_WIDTH 46
#define COSTUME_KNOB_HEIGHT 46

#define GAIN_SLIDER_Y 68
#define GAIN_SLIDER_DEFAULT_VALUE 1.0f
#define GAIN_SLIDER_MIN_VALUE 0.0f
#define GAIN_SLIDER_MAX_VALUE 1.0f
#define GAIN_SLIDER_INTERVAL 0.1f

#define PAN_SLIDER_Y 138
#define PAN_SLIDER_DEFAULT_VALUE 0.0f
#define PAN_SLIDER_MIN_VALUE -1.0f
#define PAN_SLIDER_MAX_VALUE 1.0f
#define PAN_SLIDER_INTERVAL 0.2f

#define DISTORTION_MIX_SLIDER_Y 208
#define DISTORTION_MIX_SLIDER_DEFAULT_VALUE 1.0f
#define DISTORTION_MIX_SLIDER_MIN_VALUE 0.0f
#define DISTORTION_MIX_SLIDER_MAX_VALUE 1.0f
#define DISTORTION_MIX_SLIDER_INTERVAL 0.1f

#define PHASER_MIX_SLIDER_Y 278
#define PHASER_MIX_SLIDER_DEFAULT_VALUE 0.0f
#define PHASER_MIX_SLIDER_MIN_VALUE 0.0f
#define PHASER_MIX_SLIDER_MAX_VALUE 1.0f
#define PHASER_MIX_SLIDER_INTERVAL 0.1f

#define REVERB_MIX_SLIDER_Y 348
#define REVERB_MIX_SLIDER_DEFAULT_VALUE 0.0f
#define REVERB_MIX_SLIDER_MIN_VALUE 0.0f
#define REVERB_MIX_SLIDER_MAX_VALUE 1.0f
#define REVERB_MIX_SLIDER_INTERVAL 0.1f


// General Settings

#define GNRL_DELAY_TIME_SLIDER_BOUNDS {753, 500, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define GNRL_DELAY_TIME_SLIDER_DEFAULT_VALUE 0.6f
#define GNRL_DELAY_TIME_SLIDER_MIN_VALUE 0.2f
#define GNRL_DELAY_TIME_SLIDER_MAX_VALUE 2.0f
#define GNRL_DELAY_TIME_SLIDER_INTERVAL 0.01f

#define GNRL_FEEDBACK_SLIDER_BOUNDS {895, 500, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define GNRL_FEEDBACK_SLIDER_DEFAULT_VALUE 0.7f
#define GNRL_FEEDBACK_SLIDER_MIN_VALUE 0.0f
#define GNRL_FEEDBACK_SLIDER_MAX_VALUE 0.95f
#define GNRL_FEEDBACK_SLIDER_INTERVAL 0.01f

#define GNRL_DRY_LEVEL_SLIDER_BOUNDS {752, 580, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define GNRL_DRY_LEVEL_SLIDER_DEFAULT_VALUE 0.8f
#define GNRL_DRY_LEVEL_SLIDER_MIN_VALUE 0.0f
#define GNRL_DRY_LEVEL_SLIDER_MAX_VALUE 1.0f
#define GNRL_DRY_LEVEL_SLIDER_INTERVAL 0.01f

#define GNRL_WET_LEVEL_SLIDER_BOUNDS {895, 580, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define GNRL_WET_LEVEL_SLIDER_DEFAULT_VALUE 0.8f
#define GNRL_WET_LEVEL_SLIDER_MIN_VALUE 0.0f
#define GNRL_WET_LEVEL_SLIDER_MAX_VALUE 1.0f
#define GNRL_WET_LEVEL_SLIDER_INTERVAL 0.01f

// Distortion Settings

typedef enum
{
    distType_SoftClip = 0,
    distType_HardClip = 1,
    distType_Exponential = 2,
    distType_Foldback = 3,
    distType_numberOfTypes = 4
}DistortionType;

#define DISTORTION_KNOB_WIDTH 34
#define DISTORTION_KNOB_HEIGHT 24

#define DISTORTION_TYPE_SLIDER_BOUNDS {30, 490, 40, 117}
#define DISTORTION_TYPE_SLIDER_DEFAULT_VALUE 0.0f
#define DISTORTION_TYPE_SLIDER_MIN_VALUE 0.0f
#define DISTORTION_TYPE_SLIDER_MAX_VALUE 3.0f
#define DISTORTION_TYPE_SLIDER_INTERVAL 1.0f

#define DISTORTION_DRIVE_SLIDER_BOUNDS {164, 500, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define DISTORTION_DRIVE_SLIDER_DEFAULT_VALUE 2.0f
#define DISTORTION_DRIVE_SLIDER_MIN_VALUE 1.0f
#define DISTORTION_DRIVE_SLIDER_MAX_VALUE 7.0f
#define DISTORTION_DRIVE_SLIDER_INTERVAL 0.1f

#define DISTORTION_THRESHOLD_SLIDER_BOUNDS {164, 580, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define DISTORTION_THRESHOLD_SLIDER_DEFAULT_VALUE 0.5f
#define DISTORTION_THRESHOLD_SLIDER_MIN_VALUE 0.0f
#define DISTORTION_THRESHOLD_SLIDER_MAX_VALUE 1.0f
#define DISTORTION_THRESHOLD_SLIDER_INTERVAL 0.01f


// Phaser Settings

typedef enum
{
    phaserLFOType_Sine = 0,
    phaserLFOType_Triangle = 1,
    phaserLFOType_SawUp = 2,
    phaserLFOType_SawDown = 3,
    phaserLFOType_Square = 4,
    phaserLFOType_numberOfTypes = 5
}PhaserLFOType;

#define PHASER_TYPE_SLIDER_BOUNDS {267, 579, 68, 50}
#define PHASER_TYPE_SLIDER_DEFAULT_VALUE 0.0f
#define PHASER_TYPE_SLIDER_MIN_VALUE 0.0f
#define PHASER_TYPE_SLIDER_MAX_VALUE 4.0f
#define PHASER_TYPE_SLIDER_INTERVAL 1.0f

#define PHASER_RATE_SLIDER_BOUNDS {274, 500, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define PHASER_RATE_SLIDER_DEFAULT_VALUE 4.0f
#define PHASER_RATE_SLIDER_SKEW_MID_POINT 8.0f
#define PHASER_RATE_SLIDER_MIN_VALUE 1.0f
#define PHASER_RATE_SLIDER_MAX_VALUE 50.0f

#define PHASER_DEPTH_SLIDER_BOUNDS {415, 500, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define PHASER_DEPTH_SLIDER_DEFAULT_VALUE 0.5f
#define PHASER_DEPTH_SLIDER_MIN_VALUE 0.0f
#define PHASER_DEPTH_SLIDER_MAX_VALUE 1.0f
#define PHASER_DEPTH_SLIDER_INTERVAL 0.01f

#define PHASER_FREQ_SLIDER_BOUNDS {415, 580, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define PHASER_FREQ_SLIDER_SKEW_MID_POINT 1000.0f
#define PHASER_FREQ_SLIDER_DEFAULT_VALUE 4000.0f
#define PHASER_FREQ_SLIDER_MIN_VALUE 600.0f
#define PHASER_FREQ_SLIDER_MAX_VALUE 12000.0f
//#define PHASER_FREQ_SLIDER_INTERVAL 1.0f

// Reverb Settings

#define REVERB_ROOM_SIZE_SLIDER_BOUNDS {513, 500, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define REVERB_ROOM_SIZE_SLIDER_DEFAULT_VALUE 0.5f
#define REVERB_ROOM_SIZE_SLIDER_MIN_VALUE 0.0f
#define REVERB_ROOM_SIZE_SLIDER_MAX_VALUE 1.0f
#define REVERB_ROOM_SIZE_SLIDER_INTERVAL 0.01f

#define REVERB_DAMPING_SLIDER_BOUNDS {655, 500, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define REVERB_DAMPING_SLIDER_DEFAULT_VALUE 0.5f
#define REVERB_DAMPING_SLIDER_MIN_VALUE 0.0f
#define REVERB_DAMPING_SLIDER_MAX_VALUE 1.0f
#define REVERB_DAMPING_SLIDER_INTERVAL 0.01f

#define REVERB_WIDTH_SLIDER_BOUNDS {587, 580, COSTUME_KNOB_WIDTH, COSTUME_KNOB_HEIGHT}
#define REVERB_WIDTH_SLIDER_DEFAULT_VALUE 0.5f
#define REVERB_WIDTH_SLIDER_MIN_VALUE 0.0f
#define REVERB_WIDTH_SLIDER_MAX_VALUE 1.0f
#define REVERB_WIDTH_SLIDER_INTERVAL 0.01f