/*
  ==============================================================================

    Configs.h
    Created: 24 Oct 2025 4:17:11pm
    Author:  MayTigerStation

  ==============================================================================
*/

#pragma once

// set defines for different configurations

#define SCREEN_WIDTH 975
#define SCREEN_HEIGHT 650

#define FPS 60

// Slider values and positions

#define TILE_SLIDER_WIDTH 28
#define TILE_SLIDER_HEIGHT 11

#define TILE_SLIDER_BG_WIDTH 40
#define TILE_SLIDER_BG_HEIGHT 67

#define TILE_SLIDER_STARTING_X 145
#define TILE_SLIDER_GAP_X 51

#define GAIN_SLIDER_Y 68
#define GAIN_SLIDER_DEFAULT_VALUE 1.0f
#define GAIN_SLIDER_MIN_VALUE 0.0f
#define GAIN_SLIDER_MAX_VALUE 1.0f
#define GAIN_SLIDER_INTERVAL 0.1f

#define PAN_SLIDER_Y 138
#define PAN_SLIDER_DEFAULT_VALUE 0.0f
#define PAN_SLIDER_MIN_VALUE -1.0f
#define PAN_SLIDER_MAX_VALUE 1.0f
#define PAN_SLIDER_INTERVAL 0.1f

#define DISTORTION_MIX_SLIDER_Y 208
#define DISTORTION_MIX_SLIDER_DEFAULT_VALUE 0.8f
#define DISTORTION_MIX_SLIDER_MIN_VALUE 0.0f
#define DISTORTION_MIX_SLIDER_MAX_VALUE 1.0f
#define DISTORTION_MIX_SLIDER_INTERVAL 0.1f

#define REVERB_MIX_SLIDER_Y 278
#define REVERB_MIX_SLIDER_DEFAULT_VALUE 0.0f
#define REVERB_MIX_SLIDER_MIN_VALUE 0.0f
#define REVERB_MIX_SLIDER_MAX_VALUE 1.0f
#define REVERB_MIX_SLIDER_INTERVAL 0.1f

#define PHASER_MIX_SLIDER_Y 348
#define PHASER_MIX_SLIDER_DEFAULT_VALUE 0.0f
#define PHASER_MIX_SLIDER_MIN_VALUE 0.0f
#define PHASER_MIX_SLIDER_MAX_VALUE 1.0f
#define PHASER_MIX_SLIDER_INTERVAL 0.1f

#define GNRL_DELAY_TIME_SLIDER_BOUNDS {750, 470, 80, 80}
#define GNRL_DELAY_TIME_SLIDER_DEFAULT_VALUE 0.5f
#define GNRL_DELAY_TIME_SLIDER_MIN_VALUE 0.2f
#define GNRL_DELAY_TIME_SLIDER_MAX_VALUE 2.0f
#define GNRL_DELAY_TIME_SLIDER_INTERVAL 0.01f

#define GNRL_FEEDBACK_SLIDER_BOUNDS {850, 470, 80, 80}
#define GNRL_FEEDBACK_SLIDER_DEFAULT_VALUE 0.7f
#define GNRL_FEEDBACK_SLIDER_MIN_VALUE 0.0f
#define GNRL_FEEDBACK_SLIDER_MAX_VALUE 0.95f
#define GNRL_FEEDBACK_SLIDER_INTERVAL 0.01f

#define GNRL_DRY_LEVEL_SLIDER_BOUNDS {750, 550, 80, 80}
#define GNRL_DRY_LEVEL_SLIDER_DEFAULT_VALUE 0.8f
#define GNRL_DRY_LEVEL_SLIDER_MIN_VALUE 0.0f
#define GNRL_DRY_LEVEL_SLIDER_MAX_VALUE 1.0f
#define GNRL_DRY_LEVEL_SLIDER_INTERVAL 0.01f

#define GNRL_WET_LEVEL_SLIDER_BOUNDS {850, 550, 80, 80}
#define GNRL_WET_LEVEL_SLIDER_DEFAULT_VALUE 0.8f
#define GNRL_WET_LEVEL_SLIDER_MIN_VALUE 0.0f
#define GNRL_WET_LEVEL_SLIDER_MAX_VALUE 1.0f
#define GNRL_WET_LEVEL_SLIDER_INTERVAL 0.01f

// Distortion Settings

typedef enum
{
    distType_SoftClip = 0,
    distType_HardClip = 1,
    distType_Exponential = 2,
    distType_numberOfTypes = 3
}DistortionType;

#define DISTORTION_TYPE_COMBOBOX_BOUNDS {35, 500, 180, 30}
#define DISTORTION_TYPE_COMBOBOX_DEFAULT_INDEX 0
#define DISTORTION_TYPE_COMBOBOX_SOFTCLIP_INDEX 0
#define DISTORTION_TYPE_COMBOBOX_HARDCLIP_INDEX 1
#define DISTORTION_TYPE_COMBOBOX_EXPONENTIAL_INDEX 2

#define DISTORTION_DRIVE_SLIDER_BOUNDS {15, 550, 80, 80}
#define DISTORTION_DRIVE_SLIDER_DEFAULT_VALUE 0.8f
#define DISTORTION_DRIVE_SLIDER_MIN_VALUE 0.0f
#define DISTORTION_DRIVE_SLIDER_MAX_VALUE 1.0f
#define DISTORTION_DRIVE_SLIDER_INTERVAL 0.01f

#define DISTORTION_THRESHOLD_SLIDER_BOUNDS {170, 550, 80, 80}
#define DISTORTION_THRESHOLD_SLIDER_DEFAULT_VALUE 0.8f
#define DISTORTION_THRESHOLD_SLIDER_MIN_VALUE 0.0f
#define DISTORTION_THRESHOLD_SLIDER_MAX_VALUE 1.0f
#define DISTORTION_THRESHOLD_SLIDER_INTERVAL 0.01f


// Phaser Settings

typedef enum
{
    phaserLFOType_Sine = 0,
    phaserLFOType_Triangle = 1,
    phaserLFOType_SawUp = 2,
    phaserLFOType_SawDown = 3,
    phaserLFOType_Square = 4,
    phaserLFOType_numberOfTypes = 5
}PhaserLFOType;

#define PHASER_TYPE_COMBOBOX_BOUNDS {280, 500, 180, 30}
#define PHASER_TYPE_COMBOBOX_DEFAULT_INDEX 0
#define PHASER_TYPE_COMBOBOX_SINE_INDEX 0
#define PHASER_TYPE_COMBOBOX_TRIANGLE_INDEX 1
#define PHASER_TYPE_COMBOBOX_SAWUP_INDEX 2
#define PHASER_TYPE_COMBOBOX_SAWDOWN_INDEX 3
#define PHASER_TYPE_COMBOBOX_SQUARE_INDEX 4

#define PHASER_RATE_SLIDER_BOUNDS {265, 550, 80, 80}
#define PHASER_RATE_SLIDER_DEFAULT_VALUE 0.5f
#define PHASER_RATE_SLIDER_MIN_VALUE 0.1f
#define PHASER_RATE_SLIDER_MAX_VALUE 5.0f
#define PHASER_RATE_SLIDER_INTERVAL 0.1f

#define PHASER_DEPTH_SLIDER_BOUNDS {320, 550, 80, 80}
#define PHASER_DEPTH_SLIDER_DEFAULT_VALUE 0.5f
#define PHASER_DEPTH_SLIDER_MIN_VALUE 0.0f
#define PHASER_DEPTH_SLIDER_MAX_VALUE 1.0f
#define PHASER_DEPTH_SLIDER_INTERVAL 0.01f

#define PHASER_FEEDBACK_SLIDER_BOUNDS {375, 550, 80, 80}
#define PHASER_FEEDBACK_SLIDER_DEFAULT_VALUE 0.5f
#define PHASER_FEEDBACK_SLIDER_MIN_VALUE 0.0f
#define PHASER_FEEDBACK_SLIDER_MAX_VALUE 0.95f
#define PHASER_FEEDBACK_SLIDER_INTERVAL 0.01f

// Reverb Settings

#define REVERB_ROOM_SIZE_SLIDER_BOUNDS {480, 500, 80, 80}
#define REVERB_ROOM_SIZE_SLIDER_DEFAULT_VALUE 0.5f
#define REVERB_ROOM_SIZE_SLIDER_MIN_VALUE 0.0f
#define REVERB_ROOM_SIZE_SLIDER_MAX_VALUE 1.0f
#define REVERB_ROOM_SIZE_SLIDER_INTERVAL 0.01f

#define REVERB_DAMPING_SLIDER_BOUNDS {650, 500, 80, 80}
#define REVERB_DAMPING_SLIDER_DEFAULT_VALUE 0.5f
#define REVERB_DAMPING_SLIDER_MIN_VALUE 0.0f
#define REVERB_DAMPING_SLIDER_MAX_VALUE 1.0f
#define REVERB_DAMPING_SLIDER_INTERVAL 0.01f

#define REVERB_WIDTH_SLIDER_BOUNDS {565, 550, 80, 80}
#define REVERB_WIDTH_SLIDER_DEFAULT_VALUE 0.5f
#define REVERB_WIDTH_SLIDER_MIN_VALUE 0.0f
#define REVERB_WIDTH_SLIDER_MAX_VALUE 1.0f
#define REVERB_WIDTH_SLIDER_INTERVAL 0.01f